

notify_if_user_not_defined: True # Уведомлять, если пользователь не определён в секции users
notify_not_defined_to_email: hostmaster@mycompany.ltd
smtp:
  user: noreply@mycompany.ltd
  password: mygoodpassword
  serverhost: mail.mycompany.ltd
  tcpport: 25
  tls: True
  debug: False

users:
  saymon:
    email: hostmaster@mycompany.ltd
#   Если нужно уведомлять стазу несколько пользователей по email, об аутенификации пользователя saymon, монжо настроить след. образом:
#   email:  
#     - user1@mycompany.ltd
#     - user2@mycompany.ltd
#   exclude_ips: # Айпи адреса, для которых не будет происходить проверка дополнительного пароля.
#     - 10.13.138.17
#   exclude_nets: # Подсети, для которых не будет происходить проверка дополнительного пароля.
#     - 192.168.56.0/24

