users:
  saymon:
    email: hostmaster@mycompany.ltd
#    exclude_ips: # Айпи адреса, для которых не будет происходить проверка дополнительного пароля.
#      - 10.13.138.17
#    exclude_nets: # Подсети, для которых не будет происходить проверка дополнительного пароля.
#      - 192.168.56.0/24
